package crond

import "io"

const (
	startMarker = "### this content was generated by resticprofile, please leave this line intact ###\n"
	endMarker   = "### end of resticprofile content, please leave this line intact ###\n"
)

type Crontab struct {
	name    string
	entries []Entry
	root    bool
}

func NewCrontab(name string, entries []Entry, root bool) *Crontab {
	return &Crontab{
		name:    name,
		entries: entries,
		root:    root,
	}
}

func (c *Crontab) Generate(w io.StringWriter) error {
	var err error
	if !c.root {
		_, err = w.WriteString(startMarker)
		if err != nil {
			return err
		}
	}
	if len(c.entries) > 0 {
		for _, entry := range c.entries {
			err = entry.Generate(w, c.root)
			if err != nil {
				return err
			}
		}
	}
	if !c.root {
		_, err = w.WriteString(endMarker)
		if err != nil {
			return err
		}
	}
	return nil
}
